# Site settings
author: Joan Leonard-Short
title: Joan LS
header-img: img/home-bg.png
email: jflshort@gmail.com
copyright_name: Joan Leonard-Short
description: > # this means to ignore newlines until "baseurl:"
  Data Science
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  israeljls-j

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
